layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Microformats
    web_url: https://github.com/topics/microformats
    image_url: https://raw.githubusercontent.com/github/explore/1f7cb6359d64838c4416b0cf4196483ce189776d/topics/microformats/microformats.png

  - name: IndieWeb
    web_url: https://github.com/topics/indieweb
    image_url: https://raw.githubusercontent.com/github/explore/522bed80d033d77d1bd3675f819df02ca21a2050/topics/indieweb/indieweb.png

  - name: ActivityPub
    web_url: https://github.com/topics/activitypub
    image_url: https://raw.githubusercontent.com/github/explore/df833523cdfb6fa65bb162c67405302a494d6c52/topics/activitypub/activitypub.png

  - name: WordPress
    web_url: https://github.com/topics/wordpress
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/wordpress/wordpress.png

  - name: PHP
    web_url: https://github.com/topics/php
    image_url: https://raw.githubusercontent.com/github/explore/ccc16358ac4530c6a69b1b80c7223cd2744dea83/topics/php/php.png
